# Generated by Django 2.1.5 on 2019-02-05 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='job',
            new_name='jobs',
        ),
    ]
